SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--Solution: Set transaction isolation level to SERIALIZABLE
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
	SELECT * FROM Category
	WAITFOR DELAY '00:00:08'
	SELECT * FROM Category
COMMIT TRAN